# Generated by Django 5.1.6 on 2025-02-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
