# Generated by Django 5.1.6 on 2025-02-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
